#!/usr/bin/bash -x

#doc: simple c0 ingest coalesce test

mp=$(new_kvdb) || err
kvs1=$(new_kvs $mp) || err

flushmax=100000
keymax=99999999

# This test puts and then flushes $flushmax unique keys, one at a time.
#
cmd ksync -f ${flushmax} -k ${keymax} $mp $kvs1 kvdb.c0_ingest_delay=30
cmd cn_metrics $mp $kvs1
kvsets=$(grep -c ^k "${LOG}")

cmd $sudo mpool destroy "$mp"

(( DRYRUN )) && exit 0

if (( kvsets < 10 || kvsets > flushmax / 10 )); then
    err "c0 ingest coalesce not working, found ${kvsets} kvsets"
fi

