#!/usr/bin/bash

mp=$(new_kvdb) || err

# add a KVS to the KVDB
kvs=$(new_kvs $mp) || err

# 1. Create 10000 cursors spread across 20 threads - each thread gets a few
#    cursors
# 2. Load all keys - each thread loads its share of keys
# 3. Each thread updates its cursors and each of these cursors verify a part of
#    the thread's key space

keys=$((1000 * 1000 * 4))
nthread=20
ncursor=10000
cmd multicursor_test $mp $kvs -c$keys -j$nthread -r$ncursor -l -v kvs.cn_node_size_lo=32 kvs.cn_node_size_hi=32

#
# capput tests
#
chunksz=1000
wth=96
rth=2
batchsz=500000
pwin=100
dur=30

# regular kvs
kvs=$(new_kvs $mp kvs.pfx_len=8) || err
cmd capput $mp $kvs -j$wth -t$rth -c$chunksz -b$batchsz -m$pwin -d$dur -v kvs.cn_node_size_lo=32 kvs.cn_node_size_hi=32

# capped kvs
kvs=$(new_kvs $mp kvs.pfx_len=8 kvs.kvs_ext01=1) || err
cmd capput $mp $kvs -j$wth -t$rth -c$chunksz -b$batchsz -m$pwin -d$dur -v

cmd $sudo mpool destroy "$mp"

exit 0
