#!/usr/bin/bash

#doc: Query fixed length ranges while updating random records.

mp=$(new_kvdb) || err
kvs=$(new_kvs $mp kvs.pfx_len=8) || err

# Load
nthread=128
vlen=1024
npfx=8
nsfx=200000 # (npfx * nsfx) keys total
cmd range_read $mp $kvs -l -j$nthread -v$vlen -p$npfx -s$nsfx kvs.cn_node_size_lo=32 kvs.cn_node_size_hi=32

cmd kvck $mp

# Query
nthread=32
duration=20 # seconds
range=10
cmd range_read $mp $kvs -e -b$range -j$nthread -v$vlen -p$npfx -s$nsfx -d$duration
cmd range_read $mp $kvs -e -b$range -j$nthread -v$vlen -p$npfx -s$nsfx -d$duration

cmd $sudo mpool destroy "$mp"
