#!/usr/bin/bash

#doc: kmt/kvdb insert test: 1 billion 20-byte keys with 50-byte values

mp=$(new_kvdb) || err
kvs=$(new_kvs $mp) || err

threads=$(( 2 * $(nproc) ))
keys=1g

cmd kmt -j$threads -i$keys -s1 -l50 -b $mp/$kvs kvdb.perfc_enable=1
cmd cn_metrics $mp $kvs

cmd $sudo mpool destroy "$mp"
