#!/usr/bin/env bash

#doc: quick kvdb/c0 read performance test using kmt (60s)

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT SIGTERM SIGINT SIGKILL
kvdb_create

seconds=60

kvs=$(kvs_create smoke-0) || $?
cmd kmt -i1000 -t$seconds -bcDOR -w0 -j$(nproc) -s1 "$home" $kvs
