#!/usr/bin/env bash

#doc: quick kvdb/cn performance test using kmt (60s, 20% writes)

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT SIGTERM SIGINT SIGKILL
kvdb_create

w=20
seconds=60

kvs=$(kvs_create smoke-0) || exit $?

cmd kmt -i20m -t$seconds -bcDR -s1 -w$w -j$(nproc) "$home" $kvs
