#!/usr/bin/env bash

#doc: ensure we can create 256 kvs'

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT
kvdb_create

typeset -i i=256

while (( i>0 )) ; do
    i=i-1
    cmd hse -C "$home" kvs create "kvs$i"
done

cmd kmt -i1k -t5 -cx -s1 "$home" "kvs$i"
