#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2021 Micron Technology, Inc. All rights reserved.

#doc: kvt compression test (transactional, snapshot isolation)

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT
kvdb_create

cpus=$(nproc)

cmd kvt -i1m  -T30,$((cpus * 2)) -cv -l0,16k    -ovrunlen=5 -ovcomp=1 -m1 "$home"
cmd kvt -Fi8k -T30,$((cpus * 2)) -cv -l1m -m1   -ovrunlen=3 -ovcomp=1 "$home"
cmd kvt -Fi8m -T30,$((cpus * 2)) -cv -l0,16 -m1 -ovrunlen=1 -ovcomp=1 "$home"
cmd kvt -T30,$((cpus * 2)) -cv -m1 "$home"
