#!/usr/bin/env bash

#doc: simple kvt test (transactional, snapshot isolation)

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT SIGTERM SIGINT SIGKILL
kvdb_create

cpus=$(nproc)

cmd kvt -i1000 -T60,$((cpus * 2)) -cv -l8 -m1 "$home"
