#!/usr/bin/bash

#doc: simple kvt c1 logreplay crash test (transactional, snapshot isolation)

cpus=$(nproc)

mp=$(new_kvdb) || err

cmd kvt -i1m $mp
cmd -s 9  kvt -T60,$((cpus * 2)) -ccv -l8 -m1 -K9,10,20 $mp
cmd -s 9  kvt -T60,$((cpus * 2)) -ccv -l8 -m1 -K9,15,25 $mp

cmd kvt -cv $mp
  
cmd $sudo mpool destroy "$mp"
