#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2021 Micron Technology, Inc. All rights reserved.

#doc: kmt large value test (SBUSWNF-2165)

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT
kvdb_create

kvs=$(kvs_create smoke-0) || exit $?

# This test depends on having 1MiB values in vblocks at offsets that are not
# page-aligned.  Using a small number of value lengths make that a frequent
# occurrence, thus exposing the bug (or verifying the fix) more likely.

VLEN=-l1048532:1048576

# Don't let the total size of the values exceed ~20G or 12.5% of available RAM,
# whichever is smaller.
#
typeset -i n1m

KEYS=$(awk '/^MemAvail/ {printf "%lu", $2 / (1024 * 8)}' /proc/meminfo)
if ((KEYS > 20000)) ; then
   KEYS=20000
fi

kvdb_oparams=""
kvs_oparams="kvs-oparams cn_maint_disable=true"

# ingest w spill disabled
cmd kmt "$home" $kvs -s1 $VLEN -i$KEYS  ${kvdb_oparams} ${kvs_oparams}

# verify no spill occurred
cmd cn_metrics "$home" $kvs | cmd -e grep -q n.1,

# verify keys and values
cmd kmt "$home" $kvs -s1 $VLEN -c  ${kvdb_oparams} ${kvs_oparams}

# spill
cmd putbin "$home" $kvs -n 1000 kvs-oparms cn_close_wait=true

# verify spill has occurred
cmd cn_metrics "$home" $kvs | cmd grep -q n.1,

# verify keys and values
cmd kmt "$home" $kvs -s1 $VLEN -c ${kvdb_oparams} ${kvs_oparams}
