#!/usr/bin/env bash

# Check cursor behaviour with corner cases.
# Note that this test depends on the
# way putbin creates its keys. Any change to that will affect the results of
# this test.

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT
kvdb_create

kvs=$(kvs_create smoke-0) || exit $?

nkeys=1000

# load w/ little endian fmt keys
cmd putbin "$home" $kvs -c$nkeys -e kvs-oparms cn_maint_disable=1

# create a cursor using the last key in pg 0 of the wbtree as a prefix
key=0x7f010000
cnt=$(awk '{print($1);exit(0)}' <<<$(cmd pscan "$home" $kvs -p$key -c kvs-oparms cn_maint_disable=1))
[[ "$cnt" == "1" ]] ||
    err "Forward cursor didn't find key '$key'"

cnt=$(awk '{print($1);exit(0)}' <<<$(cmd pscan "$home" $kvs -p$key -c -r kvs-oparms cn_maint_disable=1))
[[ "$cnt" == "1" ]] ||
    err "Reverse cursor didn't find key '$key'"
