#!/usr/bin/bash

# Check cursor behaviour with corner cases.
# Note that this test depends on the
# way putbin creates its keys. Any change to that will affect the results of
# this test.

mp=$(new_kvdb) || err
kvs=$(new_kvs $mp) || err

nkeys=1000

# load w/ little endian fmt keys
cmd putbin $mp $kvs -c$nkeys -e kvs.cn_maint_disable=1

# create a cursor using the last key in pg 0 of the wbtree as a prefix
key=0x7f010000
cmd pscan $mp $kvs -p${key} -c kvs.cn_maint_disable=1
cnt=$(grep -v CMD $LOG | awk '{print $1}')
if [ ${cnt} -ne 1 ]; then
    echo "Forward cursor didn't find expected key ${key}" >&2
    exit 1
fi

cmd pscan $mp $kvs -p${key} -c -r kvs.cn_maint_disable=1
cnt=$(grep -v CMD $LOG | awk '{print $1}')
if [ ${cnt} -ne 1 ]; then
    echo "Reverse cursor didn't find expected key ${key}" >&2
    exit 1
fi

cmd $sudo mpool destroy "$mp"
