#!/usr/bin/bash

#doc: 60s longtest
mp=$(new_kvdb) || err
kvs=$(new_kvs $mp) || err

keys=$((20*1000*1000))
threads=$(nproc)
seconds=60

cmd longtest $mp $kvs -t $threads -s $seconds -c $keys kvdb.perfc_enable=1
cmd cn_metrics $mp $kvs

cmd $sudo mpool destroy "$mp"


