#!/usr/bin/bash

#doc: quick longtest focused on cn
mp=$(new_kvdb) || err
kvs=$(new_kvs $mp) || err

threads=4
keys=100000
seed=$RANDOM

# This test requires '--once' to ensure each thread of each invocation of
# longtest runs through exactly one iteration.
for (( phase = 0; phase <= 9; phase++ )); do
    cmd longtest $mp $kvs --seed $seed -t $threads -i 3 -c $keys --mphase $((1<<phase)) --verify 100 --once -v
    cmd cn_metrics $mp $kvs
done

cmd $sudo mpool destroy "$mp"
