#!/usr/bin/env bash

#tdoc: mcache data integrity test

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT SIGTERM SIGINT SIGKILL
kvdb_create

seconds=60

storage="$home/capacity/smoke-mdc-test"

cmd rm -fr $storage
cmd mkdir $storage

cmd mpiotest -T $seconds $storage

cmd rm -fr $storage
