#!/usr/bin/env bash

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT SIGTERM SIGINT SIGKILL
kvdb_create

# add a KVS to the KVDB
# fanout=16 for a smaller pivot level
kvs=$(kvs_create smoke-0 fanout=16 pfx_len=8 sfx_len=8) || exit $?

p=10000
c=1000
s=10
threads=96

oparms=(
    kvdb-oparms
    csched_samp_max=100
    kvs-oparms
    cn_node_size_hi=128
    cn_node_size_lo=128)

# Use probe
cmd pfx_probe "$home" $kvs -p$p -c$c -s$s -j$threads "${oparms[@]}"

# Use cursors; skip load
cmd pfx_probe "$home" $kvs -p$p -c$c -s$s -j$threads -v -x -d15 "${oparms[@]}"

# Use gets; skip load
cmd pfx_probe "$home" $kvs -p$p -c$c -s$s -j$threads -v -g -d15 "${oparms[@]}"
