#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2021 Micron Technology, Inc. All rights reserved.

#doc: test ptree semantics

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT
kvdb_create

kvs=$(kvs_create smoke-0 pfx_len=8) || exit $?

# Test 1: Should result in 2 kblocks
keys=1300000
ptombs=300000

rparams='kvs-oparms cn_maint_disable=true'

cmd ptree-overload "$home" $kvs -k $keys -p $ptombs ${rparams}
cn_metrics "$home" $kvs
nkvset=$(cn_metrics "$home" $kvs | grep -c ^k)
[[ $nkvset == 1 ]] || err "Expected only one kvset. Found $nkvset kvsets"

nkblks=$(cn_metrics "$home" $kvs | awk '$1 ~ /^k/ {print $14}')
[[ $nkblks == 2 ]] || err "Expected two kblocks. Found $nkblks kblocks"

# Test 2: Should result in 1 kblock
kvs=$(kvs_create pfx_len=8) || err
keys=1000000
ptombs=300000

cmd ptree-overload "$home" $kvs -k $keys -p $ptombs ${rparams}
cn_metrics "$home" $kvs
nkvset=$(cn_metrics "$home" $kvs | grep -c ^k)
[[ $nkvset == 1 ]] || err "Expected only one kvset. Found $nkvset kvsets"

nkblks=$(cn_metrics "$home" $kvs | awk '$1 ~ /^k/ {print $14}')
[[ $nkblks == 1 ]] || err "Expected one kblock. Found $nkblks kblocks"
