#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2021 Micron Technology, Inc. All rights reserved.

#doc: samples test

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

fbase="$home/large_val"

end () {
    rm -fr $fbase*
    kvdb_drop
}

trap end EXIT

cmd ex1_create "$home" skvs0 skvs1 skvs2 skvs3 skvs4
cmd ex2_simple_ops "$home" skvs0
cmd ex3_cursor "$home" skvs1
cmd ex4_transactions "$home" skvs2 skvs3
cmd ex6_error_handling

for ((n=1; n<10; n++)); do
    cmd dd bs=1000000 count=$n if=/dev/urandom of=$fbase$n
done

cmd ex5_large_val "$home" skvs4 $fbase*
cmd ex5_large_val "$home" skvs4 -x $fbase*
cmd chmod 644 $fbase*.out

for ((n=1; n<10; n++)); do
    cmd cmp $fbase$n $fbase$n.out
done
