#!/usr/bin/env bash

#doc: simple_client test

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT
kvdb_create

keys=1000
kvs=$(kvs_create smoke-0) || exit $?
cmd simple_client "$home" $kvs -c $keys
