#!/usr/bin/bash

#doc: test hse1 version command

X=$(hse1 -Vv |grep -c '^version:')
[ $X -eq 1 ] || err

X=$(hse1 --version -v |grep -c '^tag:')
[ $X -eq 1 ] || err

X=$(hse1 --version --verbose |grep -c '^sha:')
[ $X -eq 1 ] || err

VOPT=$(hse1 -V)
[ ! -z "${VOPT}" ] || err
