#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2021 Micron Technology, Inc. All rights reserved.

#doc: test HSE CLI version command

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

output=$(hse -Vv) || exit $?

# Check for three lines of output
count=$(wc -l <<<"$output") || exit $?
if [[ "$count" != 3 ]]; then
    err "Expect three lines of output from command:" \
        "hse -Vv" \
        "\nFound $count lines"
fi

# Check output fields
fields=$(sort <<<$(sed -ne 's/:.*//p' <<<"$output") | xargs)
[[ "$fields" == "sha tag version" ]] ||
    err "Expect fields: sha, tag and version" \
        "\nFound: $fields"
