#!/usr/bin/env bash

#doc: use putgetdel to test zero-length values

source $(dirname "${BASH_SOURCE[0]}")/smoke.subr

trap kvdb_drop EXIT
kvdb_create

keys=100
kvs=$(kvs_create smoke-0) || exit $?

# Six step test:
# - Put keys with 0-byte values
# - Verify those keys can be found and have vlen==0
# - Update same keys with 10-byte values
# - Verify
# - Update same keys with 0-byte values
# - Verify
cmd putgetdel "$home" $kvs -c $keys --vlen 0   --put
cmd putgetdel "$home" $kvs -c $keys --vlen 0  --vput
cmd putgetdel "$home" $kvs -c $keys --vlen 10  --put
cmd putgetdel "$home" $kvs -c $keys --vlen 10 --vput
cmd putgetdel "$home" $kvs -c $keys --vlen 0   --put
cmd putgetdel "$home" $kvs -c $keys --vlen 0  --vput
