/* this file is auto-generated by cndblog2c.awk, see Readme.txt */ /* do not edit, see top of file for instructions */
void                                           /* do not edit, see top of file for instructions */
inject_raw(                                    /* do not edit, see top of file for instructions */
           struct mpool_mdc *mdc)              /* do not edit, see top of file for instructions */
{                                              /* do not edit, see top of file for instructions */
    struct cndb_ver_omf  ver = {};             /* do not edit, see top of file for instructions */
    struct cndb_info_omf info = {};            /* do not edit, see top of file for instructions */
    struct cndb_tx_omf   tx = {};              /* do not edit, see top of file for instructions */
    struct cndb_txc_omf  txc = {};             /* do not edit, see top of file for instructions */
    struct cndb_txm_omf  txm = {};             /* do not edit, see top of file for instructions */
    struct cndb_ack_omf  ack = {};             /* do not edit, see top of file for instructions */
    struct cndb_oid_omf *oidv = NULL;          /* do not edit, see top of file for instructions */
    char   cndb_buf[CNDB_CBUFSZ_DEFAULT] = {}; /* do not edit, see top of file for instructions */
    merr_t err = 0;                            /* do not edit, see top of file for instructions */
    int    i;                                  /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(
        &ver.hdr, CNDB_TYPE_VERSION); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &ver.hdr,
        (sizeof(ver) + 0) - sizeof(ver.hdr)); /* do not edit, see top of file for instructions */
    omf_set_cnver_magic(&ver, 0x32313132);    /* do not edit, see top of file for instructions */
    omf_set_cnver_version(&ver, 7);           /* do not edit, see top of file for instructions */
    omf_set_cnver_captgt(&ver, 616562688);    /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &ver, sizeof(ver), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cninfo_cnid(&info, 2);        /* do not edit, see top of file for instructions */
    omf_set_cninfo_fanout_bits(&info, 3); /* do not edit, see top of file for instructions */
    omf_set_cninfo_prefix_len(&info, 0);  /* do not edit, see top of file for instructions */
    omf_set_cninfo_flags(&info, 0x0);     /* do not edit, see top of file for instructions */
    omf_set_cninfo_metasz(&info, 4);      /* do not edit, see top of file for instructions */
    omf_set_cninfo_name(
        &info, "kvs2", strlen("kvs2"));    /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf)); /* do not edit, see top of file for instructions */
    i = sizeof(info);                      /* do not edit, see top of file for instructions */
    cndb_buf[i++] = 0xca;                  /* do not edit, see top of file for instructions */
    cndb_buf[i++] = 0xfe;                  /* do not edit, see top of file for instructions */
    cndb_buf[i++] = 0xba;                  /* do not edit, see top of file for instructions */
    cndb_buf[i++] = 0xbe;                  /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(
        &info.hdr, CNDB_TYPE_INFO); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &info.hdr,
        (sizeof(info) + 4) - sizeof(info.hdr)); /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &info, sizeof(info));      /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, cndb_buf, sizeof(info) + 4, false); /* do not edit, see top of file for instructions */
    if (ev(err))                                 /* do not edit, see top of file for instructions */
        goto errout;                             /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cninfo_cnid(&info, 3);        /* do not edit, see top of file for instructions */
    omf_set_cninfo_fanout_bits(&info, 3); /* do not edit, see top of file for instructions */
    omf_set_cninfo_prefix_len(&info, 2);  /* do not edit, see top of file for instructions */
    omf_set_cninfo_flags(&info, 0x0);     /* do not edit, see top of file for instructions */
    omf_set_cninfo_metasz(&info, 2);      /* do not edit, see top of file for instructions */
    omf_set_cninfo_name(
        &info, "kvs3", strlen("kvs3"));    /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf)); /* do not edit, see top of file for instructions */
    i = sizeof(info);                      /* do not edit, see top of file for instructions */
    cndb_buf[i++] = 0xfe;                  /* do not edit, see top of file for instructions */
    cndb_buf[i++] = 0xed;                  /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(
        &info.hdr, CNDB_TYPE_INFO); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &info.hdr,
        (sizeof(info) + 2) - sizeof(info.hdr)); /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &info, sizeof(info));      /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, cndb_buf, sizeof(info) + 2, false); /* do not edit, see top of file for instructions */
    if (ev(err))                                 /* do not edit, see top of file for instructions */
        goto errout;                             /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cninfo_cnid(&info, 4);        /* do not edit, see top of file for instructions */
    omf_set_cninfo_fanout_bits(&info, 3); /* do not edit, see top of file for instructions */
    omf_set_cninfo_prefix_len(&info, 3);  /* do not edit, see top of file for instructions */
    omf_set_cninfo_flags(&info, 0x0);     /* do not edit, see top of file for instructions */
    omf_set_cninfo_metasz(&info, 4);      /* do not edit, see top of file for instructions */
    omf_set_cninfo_name(
        &info, "kvs4", strlen("kvs4"));    /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf)); /* do not edit, see top of file for instructions */
    i = sizeof(info);                      /* do not edit, see top of file for instructions */
    cndb_buf[i++] = 0x21;                  /* do not edit, see top of file for instructions */
    cndb_buf[i++] = 0x12;                  /* do not edit, see top of file for instructions */
    cndb_buf[i++] = 0x12;                  /* do not edit, see top of file for instructions */
    cndb_buf[i++] = 0x21;                  /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(
        &info.hdr, CNDB_TYPE_INFO); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &info.hdr,
        (sizeof(info) + 4) - sizeof(info.hdr)); /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &info, sizeof(info));      /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, cndb_buf, sizeof(info) + 4, false); /* do not edit, see top of file for instructions */
    if (ev(err))                                 /* do not edit, see top of file for instructions */
        goto errout;                             /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&tx.hdr, CNDB_TYPE_TX); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &tx.hdr,
        (sizeof(tx) + 0) - sizeof(tx.hdr)); /* do not edit, see top of file for instructions */
    omf_set_tx_id(&tx, 3);                  /* do not edit, see top of file for instructions */
    omf_set_tx_seqno(&tx, 0);               /* do not edit, see top of file for instructions */
    omf_set_tx_nc(&tx, 0);                  /* do not edit, see top of file for instructions */
    omf_set_tx_nd(&tx, 8);                  /* do not edit, see top of file for instructions */
    omf_set_tx_ingestid(&tx, 0);            /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &tx, sizeof(tx), false); /* do not edit, see top of file for instructions */
    if (ev(err))                      /* do not edit, see top of file for instructions */
        goto errout;                  /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&ack.hdr, CNDB_TYPE_ACK); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &ack.hdr,
        (sizeof(ack) + 0) - sizeof(ack.hdr)); /* do not edit, see top of file for instructions */
    omf_set_ack_txid(&ack, 3);                /* do not edit, see top of file for instructions */
    omf_set_ack_tag(&ack, 0);                 /* do not edit, see top of file for instructions */
    omf_set_ack_cnid(&ack, 0);                /* do not edit, see top of file for instructions */
    omf_set_ack_type(&ack, CNDB_ACK_TYPE_C);  /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &ack, sizeof(ack), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 3);                     /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 3);                    /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 2);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 2);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 2);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x0012610e);        /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00000002);        /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00000003);        /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00000004);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 3);                     /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 4);                    /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 2);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00126101);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 3);                     /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 5);                    /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 4);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00127102);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 3);                     /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 6);                    /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 2);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00127103);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 3);                     /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 7);                    /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 2);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00125104);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 3);                     /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 8);                    /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 2);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00119105);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 3);                     /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 9);                    /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 2);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00111106);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 3);                     /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 10);                   /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 2);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x0011d107);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 3);                  /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 3);                 /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 2);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 0);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 3);                  /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 4);                 /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 2);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 1);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 3);                  /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 5);                 /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 4);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 2);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 3);                  /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 6);                 /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 2);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 3);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 3);                  /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 7);                 /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 2);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 4);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 3);                  /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 8);                 /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 2);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 5);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 3);                  /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 9);                 /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 2);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 6);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 3);                  /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 10);                /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 2);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 7);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&tx.hdr, CNDB_TYPE_TX); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &tx.hdr,
        (sizeof(tx) + 0) - sizeof(tx.hdr)); /* do not edit, see top of file for instructions */
    omf_set_tx_id(&tx, 14);                 /* do not edit, see top of file for instructions */
    omf_set_tx_seqno(&tx, 0);               /* do not edit, see top of file for instructions */
    omf_set_tx_nc(&tx, 1);                  /* do not edit, see top of file for instructions */
    omf_set_tx_nd(&tx, 2);                  /* do not edit, see top of file for instructions */
    omf_set_tx_ingestid(&tx, 0);            /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &tx, sizeof(tx), false); /* do not edit, see top of file for instructions */
    if (ev(err))                      /* do not edit, see top of file for instructions */
        goto errout;                  /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&ack.hdr, CNDB_TYPE_ACK); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &ack.hdr,
        (sizeof(ack) + 0) - sizeof(ack.hdr)); /* do not edit, see top of file for instructions */
    omf_set_ack_txid(&ack, 14);               /* do not edit, see top of file for instructions */
    omf_set_ack_tag(&ack, 0);                 /* do not edit, see top of file for instructions */
    omf_set_ack_cnid(&ack, 0);                /* do not edit, see top of file for instructions */
    omf_set_ack_type(&ack, CNDB_ACK_TYPE_C);  /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &ack, sizeof(ack), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 14);                    /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 16);                   /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 3);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x0012410a);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 14);                    /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 18);                   /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 3);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x0012610b);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 14);                 /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 16);                /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 3);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 2);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 14);                 /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 18);                /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 3);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 4);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&tx.hdr, CNDB_TYPE_TX); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &tx.hdr,
        (sizeof(tx) + 0) - sizeof(tx.hdr)); /* do not edit, see top of file for instructions */
    omf_set_tx_id(&tx, 21);                 /* do not edit, see top of file for instructions */
    omf_set_tx_seqno(&tx, 0);               /* do not edit, see top of file for instructions */
    omf_set_tx_nc(&tx, 2);                  /* do not edit, see top of file for instructions */
    omf_set_tx_nd(&tx, 8);                  /* do not edit, see top of file for instructions */
    omf_set_tx_ingestid(&tx, 0);            /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &tx, sizeof(tx), false); /* do not edit, see top of file for instructions */
    if (ev(err))                      /* do not edit, see top of file for instructions */
        goto errout;                  /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&ack.hdr, CNDB_TYPE_ACK); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &ack.hdr,
        (sizeof(ack) + 0) - sizeof(ack.hdr)); /* do not edit, see top of file for instructions */
    omf_set_ack_txid(&ack, 21);               /* do not edit, see top of file for instructions */
    omf_set_ack_tag(&ack, 0);                 /* do not edit, see top of file for instructions */
    omf_set_ack_cnid(&ack, 0);                /* do not edit, see top of file for instructions */
    omf_set_ack_type(&ack, CNDB_ACK_TYPE_C);  /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &ack, sizeof(ack), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 21);                    /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 21);                   /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 4);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x0012710e);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 21);                    /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 22);                   /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 4);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x0012610f);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 21);                    /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 23);                   /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 4);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00126110);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 21);                    /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 24);                   /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 4);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00128103);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 21);                    /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 25);                   /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 2);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00126104);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 21);                    /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 26);                   /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 4);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x0011a105);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 21);                    /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 27);                   /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 4);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x00112106);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_txc_id(&txc, 21);                    /* do not edit, see top of file for instructions */
    omf_set_txc_tag(&txc, 28);                   /* do not edit, see top of file for instructions */
    omf_set_txc_cnid(&txc, 4);                   /* do not edit, see top of file for instructions */
    omf_set_txc_keepvbc(&txc, 0);                /* do not edit, see top of file for instructions */
    omf_set_txc_kcnt(&txc, 1);                   /* do not edit, see top of file for instructions */
    omf_set_txc_vcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    omf_set_txc_mcnt(&txc, 0);                   /* do not edit, see top of file for instructions */
    memset(cndb_buf, 0, sizeof(cndb_buf));       /* do not edit, see top of file for instructions */
    oidv = (void *)&cndb_buf[sizeof(txc)];       /* do not edit, see top of file for instructions */
    omf_set_cndb_oid(oidv++, 0x0011e107);        /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txc.hdr, CNDB_TYPE_TXC); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txc.hdr,
        (sizeof(txc) + (char *)oidv - &cndb_buf[sizeof(txc)]) -
            sizeof(txc.hdr));            /* do not edit, see top of file for instructions */
    memcpy(cndb_buf, &txc, sizeof(txc)); /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc,
        cndb_buf,
        (char *)oidv - cndb_buf,
        false);      /* do not edit, see top of file for instructions */
    if (ev(err))     /* do not edit, see top of file for instructions */
        goto errout; /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 21);                 /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 21);                /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 4);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 0);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 21);                 /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 22);                /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 4);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 1);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 21);                 /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 23);                /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 4);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 2);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 21);                 /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 24);                /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 4);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 3);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 21);                 /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 25);                /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 2);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 4);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 21);                 /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 26);                /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 4);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 5);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 21);                 /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 27);                /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 4);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 6);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    omf_set_cnhdr_type(&txm.hdr, CNDB_TYPE_TXM); /* do not edit, see top of file for instructions */
    omf_set_cnhdr_len(
        &txm.hdr,
        (sizeof(txm) + 0) - sizeof(txm.hdr)); /* do not edit, see top of file for instructions */
    omf_set_txm_id(&txm, 21);                 /* do not edit, see top of file for instructions */
    omf_set_txm_tag(&txm, 28);                /* do not edit, see top of file for instructions */
    omf_set_txm_cnid(&txm, 4);                /* do not edit, see top of file for instructions */
    omf_set_txm_dgen(&txm, 1);                /* do not edit, see top of file for instructions */
    omf_set_txm_level(&txm, 1);               /* do not edit, see top of file for instructions */
    omf_set_txm_offset(&txm, 7);              /* do not edit, see top of file for instructions */
    omf_set_txm_vused(&txm, 0);               /* do not edit, see top of file for instructions */
    omf_set_txm_compc(&txm, 0);               /* do not edit, see top of file for instructions */
    err = mpool_mdc_append(
        mdc, &txm, sizeof(txm), false); /* do not edit, see top of file for instructions */
    if (ev(err))                        /* do not edit, see top of file for instructions */
        goto errout;                    /* do not edit, see top of file for instructions */
    /* do not edit, see top of file for instructions */
    return;                       /* do not edit, see top of file for instructions */
                                  /* do not edit, see top of file for instructions */
errout:                           /* do not edit, see top of file for instructions */
    fatal((char *)__func__, err); /* do not edit, see top of file for instructions */
} /* do not edit, see top of file for instructions */
  /* do not edit, see top of file for instructions */
