name: Bug Report
description: Create a bug report to help us improve the project.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening an issue. Please be sure to review contributing guidelines.
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Build and install from master
        2. Configure your system
        3. Run some commands
        4. See error in logs
  - type: input
    id: os
    attributes:
      label: Linux Distribution
      placeholder: Ubuntu 18.04
    validations:
      required: true
  - type: input
    id: fs
    attributes:
      label: File System
      placeholder: xfs
    validations:
      required: true
  - type: input
    id: platform-other
    attributes:
      label: Other System details
      placeholder: |
        CPU: 6 cores 
        Memory: 32 GB 
        Storage: 512 GB SSD
