# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2021 Micron Technology, Inc.

blank_issues_enabled: false
contact_links:
  - name: HSE Discussions
    url: https://github.com/hse-project/hse/discussions
    about: Please ask and answer questions here.
