/* SPDX-License-Identifier: Apache-2.0
 *
 * Copyright (C) 2022 Tristan Partin <tristan@partin.io> All rights reserved.
 */

#include <getopt.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sysexits.h>

#include <clang-c/Index.h>
#include <clang-c/CXCompilationDatabase.h>

#include "header.h"
#include "mkmock.h"
#include "mock.h"

const char *group;
const char *file;

static void
generate(void)
{
    int sz;
    const char *slash, *period;

    fprintf(output, "/* GENERATED BY mkmock. DO NOT EDIT! */\n\n");

    slash = strrchr(file, '/');
    period = strrchr(file, '.');

    if (slash && !period) {
        sz = strlen(slash);
    } else if (!slash && period) {
        sz = (uintptr_t)period - (uintptr_t)file;
    } else {
        sz = period - slash - 1;
    }

    fprintf(output, "#ifndef MAPI_%s_%.*s_H\n", group, sz, slash ? slash + 1 : file);
    fprintf(output, "#define MAPI_%s_%.*s_H\n\n", group, sz, slash ? slash + 1 : file);

    fprintf(output, "#include <stdint.h>\n\n");

    fprintf(output, "#include <mock/api.h>\n\n");

    for (size_t i = 0; i < num_mocks; i++) {
        const struct mock *mock = &mocks[i];

        fprintf(output, "/* %s */\n", mock->function_name);
        fprintf(output, "typedef %s mtfm_%s_%s_fp(", mock->return_type_name, group,
            mock->function_name);
        if (mock->argc == 0 && !mock->is_variadic) {
            fprintf(output, "void");
        } else {
            for (size_t j = 0; j < mock->argc; j++) {
                const struct argument *arg = &mock->argv[j];

                if (j == mock->argc - 1 && !mock->is_variadic) {
                    fprintf(output, "%s", arg->type);
                } else {
                    fprintf(output, "%s, ", arg->type);
                }
            }
        }
        if (mock->is_variadic)
            fprintf(output, "...");
        fprintf(output, ");\n\n");

        fprintf(output, "mtfm_%s_%s_fp *\nmtfm_%s_%s_get(void);\n\n", group,
            mock->function_name, group, mock->function_name);
        fprintf(output, "mtfm_%s_%s_fp *\nmtfm_%s_%s_get_real(void);\n\n", group,
            mock->function_name, group, mock->function_name);
        fprintf(output, "void\nmtfm_%s_%s_set(mtfm_%s_%s_fp *);\n\n", group,
            mock->function_name, group, mock->function_name);

        fprintf(output, "#ifndef MTF_MOCK_IMPL_%s\n", group);
        fprintf(output, "#define %s(...) \\\n", mock->function_name);
        fprintf(output, "({ \\\n");
        switch (mock->return_type_kind) {
        case CXType_Void:
            fprintf(output, "\tif (!mapi_enabled) \\\n");
            fprintf(output, "\t\tmtfm_%s_%s_get()(__VA_ARGS__); \\\n", group,
                mock->function_name);
            fprintf(output, "\t(void)0; \\\n");
            break;
        case CXType_Pointer:
            fprintf(output, "\t%s rc = NULL; \\\n", mock->return_type_name);
            fprintf(output,
                "\tif (!mapi_enabled || !mapi_inject_check_ptr(mapi_idx_%s, (void **)&rc)) \\\n",
                mock->function_name);
            fprintf(output, "\t\trc = mtfm_%s_%s_get()(__VA_ARGS__); \\\n", group,
                mock->function_name);
            fprintf(output, "\trc; \\\n");
            break;
        default:
            fprintf(output, "\t%s rc = { 0 }; \\\n", mock->return_type_name);
            fprintf(output,
                "\tif (!mapi_enabled || !mapi_inject_check(mapi_idx_%s, (uint64_t *)&rc)) \\\n",
                mock->function_name);
            fprintf(output, "\t\trc = mtfm_%s_%s_get()(__VA_ARGS__); \\\n", group,
                mock->function_name);
            fprintf(output, "\trc; \\\n");
            break;
        }
        fprintf(output, "})\n");
        fprintf(output, "#endif /* MTF_MOCK_IMPL_%s */\n\n", group);
    }

    fprintf(output, "#endif /* MAPI_%s_%.*s_H */\n", group, sz, slash ? slash + 1 : file);
}

int
header(const int argc, char **argv)
{
    int rc;

    if (argc != 3) {
        fprintf(stderr, "header needs a group and an input file\n");
        return EX_USAGE;
    }

    group = argv[1];
    file = argv[2];

    rc = mock_collect(file);
    if (rc) {
        fprintf(stderr, "Failed to collect mocks for %s\n", file);
        return EX_UNAVAILABLE;
    }

    generate();

    return 0;
}
