/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2022 Micron Technology, Inc.  All rights reserved.
 */

#include <getopt.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <sysexits.h>

#include <clang-c/CXCompilationDatabase.h>
#include <clang-c/Index.h>

#include "mkmock.h"
#include "mock.h"
#include "source.h"

static const char *file;
static const char *group;

static void
generate(void)
{
    fprintf(output, "/* GENERATED BY mkmock. DO NOT EDIT! */\n\n");

    fprintf(output, "struct {\n");
    for (size_t i = 0; i < num_mocks; i++)
        fprintf(output, "\tmtfm_%s_%s_fp *%s;\n", group, mocks[i].function_name, mocks[i].function_name);
    fprintf(output, "} mtfm_%s_mocks;\n\n", group);

    for (size_t i = 0; i < num_mocks; i++) {
        const struct mock *mock = &mocks[i];

        fprintf(output, "/* %s */\n", mock->function_name);
        fprintf(output, "mtfm_%s_%s_fp *\n", group, mock->function_name);
        fprintf(output, "mtfm_%s_%s_get()\n", group, mock->function_name);
        fprintf(output, "{\n");
        fprintf(output, "\tif (mtfm_%s_mocks.%s)\n", group, mock->function_name);
        fprintf(output, "\t\treturn mtfm_%s_mocks.%s;\n\n", group, mock->function_name);
        fprintf(output, "\treturn %s;\n", mock->function_name);
        fprintf(output, "}\n\n");

        fprintf(output, "mtfm_%s_%s_fp *\n", group, mock->function_name);
        fprintf(output, "mtfm_%s_%s_get_real()\n", group, mock->function_name);
        fprintf(output, "{\n");
        fprintf(output, "\treturn %s;\n", mock->function_name);
        fprintf(output, "}\n\n");

        fprintf(output, "void\n");
        fprintf(output, "mtfm_%s_%s_set(mtfm_%s_%s_fp *mock)\n", group, mock->function_name,
            group, mock->function_name);
        fprintf(output, "{\n");
        fprintf(output, "\tmtfm_%s_mocks.%s = mock;\n", group, mock->function_name);
        fprintf(output, "}\n");

        if (i < num_mocks - 1)
            fputc('\n', output);
    }
}

int
source(const int argc, char **argv)
{
    int rc;

    if (argc != 3) {
        fprintf(stderr, "source needs a group and an input file\n");
        return EX_USAGE;
    }

    group = argv[1];
    file = argv[2];

    rc = mock_collect(file);
    if (rc) {
        fprintf(stderr, "Failed to collect mocks for %s\n", argv[1]);
        return EX_UNAVAILABLE;
    }

    generate();

    return 0;
}
