/* SPDX-License-Identifier: Apache-2.0 */
/*
 * Copyright (C) 2022 Micron Technology, Inc.  All rights reserved.
 */

#include <getopt.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <sysexits.h>

#include <clang-c/Index.h>
#include <clang-c/CXCompilationDatabase.h>

#include "mkmock.h"
#include "mock.h"
#include "symbol-table.h"

static void
generate(void)
{
    fprintf(output, "/* GENERATED BY mkmock. DO NOT EDIT! */\n\n");

    fprintf(output, "#ifndef MAPI_SYMBOL_TABLE_H\n");
    fprintf(output, "#define MAPI_SYMBOL_TABLE_H\n\n");

    if (num_mocks > 0) {
        fprintf(output, "enum mapi_idx {\n");
        for (size_t i = 0; i < num_mocks; i++) {
            struct mock *mock = &mocks[i];

            fprintf(output, "\tmapi_idx_%s,\n", mock->function_name);
        }
        fprintf(output, "};\n\n");

        fprintf(output, "#define MAPI_IDX_MAX mapi_idx_%s\n\n", mocks[num_mocks - 1].function_name);
    }

    fprintf(output, "#endif\n");
}

int
symbol_table(const int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "symbol-table needs at least one input file\n");
        return EX_USAGE;
    }

    for (int i = 1; i < argc; i++) {
        int rc;

        if ((rc = mock_collect(argv[i]))) {
            fprintf(stderr, "Failed to collect mocks for %s\n", argv[i]);
            return rc;
        }
    }

    generate();

    return 0;
}
