#!/usr/bin/bash

#doc: simple c1 correctness test on multiple KVSes

keys=10000
t=5   #threads
T=500

# add 5 KVSes to the KVDB
kvs1=$(new_kvs $mp) || err
kvs2=$(new_kvs $mp) || err
kvs3=$(new_kvs $mp) || err
kvs4=$(new_kvs $mp) || err
kvs5=$(new_kvs $mp) || err

kvs_list="$kvs1,$kvs2,$kvs3,$kvs4,$kvs5"

# ingest mode
cmd -s 9 $HSE_TOOLS_DIR/c1ingest $mp $kvs_list -I -v -t $t -c $keys -b -l 64 -L 64 -T $T
# verify mode
cmd $HSE_TOOLS_DIR/c1ingest $mp $kvs_list -v -t $t -c $keys -b -l 64 -L 64 -T $T

# drop one kvs and recreate it
cmd "$HSE_CLI" kvs destroy $mp/$kvs2
kvs2=$(new_kvs $mp) || err
kvs_list="$kvs1,$kvs2,$kvs3,$kvs4,$kvs5"

# ingest mode
cmd -s 9 $HSE_TOOLS_DIR/c1ingest $mp $kvs_list -I -v -t $t -c $keys -p -b -l 64 -L 64 -T $T
# verify mode
cmd $HSE_TOOLS_DIR/c1ingest $mp $kvs_list -v -t $t -c $keys -p -b -l 64 -L 64 -T $T

# drop one kvs and recreate it
cmd "$HSE_CLI" kvs destroy $mp/$kvs5
kvs5=$(new_kvs $mp) || err
kvs_list="$kvs1,$kvs2,$kvs3,$kvs4,$kvs5"

# ingest mode
cmd -s 9 $HSE_TOOLS_DIR/c1ingest $mp $kvs_list -I -v -t $t -c $keys -p -u -b -l 64 -L 64 -T $((T * 30))
# verify mode
cmd $HSE_TOOLS_DIR/c1ingest $mp $kvs_list -v -t $t -c $keys -p -u -b -l 64 -L 64 -T $T



#Run tx test
kvs1=$(new_kvs $mp) || err

# ingest mode
cmd -s 9 $HSE_TOOLS_DIR/c1ingest $mp $kvs1 -I -v -c $keys -p -u -l 64 -L 1024 -T $T -x
# verify mode
cmd $HSE_TOOLS_DIR/c1ingest $mp $kvs1 -v -c $keys -p -u -l 64 -L 1024 -T $T -x



#Run mixed mode test
kvs1=$(new_kvs $mp) || err

# ingest mode
cmd -s 9 $HSE_TOOLS_DIR/c1ingest $mp $kvs1 -I -v -c $keys -p -u -l 64 -L 1024 -T $T -m
# verify mode
cmd $HSE_TOOLS_DIR/c1ingest $mp $kvs1 -v -c $keys -p -u -l 64 -L 1024 -T $T -m


