#!/usr/bin/bash -x

#doc: simple c0 ingest coalesce test

kvs1=$(new_kvs $mp) || err

flushmax=100000
keymax=99999999

# This test puts and then flushes $flushmax unique keys, one at a time.
#
cmd $HSE_TOOLS_DIR/ksync -f ${flushmax} -k ${keymax} $mp $kvs1 kvdb.c0_ingest_delay=30
cmd $HSE_TOOLS_DIR/cn_metrics $mp $kvs1
kvsets=$(grep -c ^k "${LOG}")

if (( kvsets < 10 || kvsets > flushmax / 10 )); then
    err "c0 ingest coalesce not working, found ${kvsets} kvsets"
fi

