#!/usr/bin/bash

#doc: test cn tree spill, k-compaction and kv-compaction

setup () {
    kvs=$(new_kvs $mp) || err

    # first 6 kvsets have keys 0..999
    cmd $HSE_TOOLS_DIR/putgetdel $mp $kvs -p -s   0 -c 100 kvs.cn_maint_disable=1
    cmd $HSE_TOOLS_DIR/putgetdel $mp $kvs -p -s 100 -c 100 kvs.cn_maint_disable=1
    cmd $HSE_TOOLS_DIR/putgetdel $mp $kvs -p -s 200 -c 200 kvs.cn_maint_disable=1
    cmd $HSE_TOOLS_DIR/putgetdel $mp $kvs -p -s 400 -c 200 kvs.cn_maint_disable=1
    cmd $HSE_TOOLS_DIR/putgetdel $mp $kvs -p -s 600 -c 200 kvs.cn_maint_disable=1
    cmd $HSE_TOOLS_DIR/putgetdel $mp $kvs -p -s 800 -c 200 kvs.cn_maint_disable=1
    # next kvset: update 0..199
    cmd $HSE_TOOLS_DIR/putgetdel $mp $kvs -u -s   0 -c 200 kvs.cn_maint_disable=1
    # next kvset: delete 100.299
    cmd $HSE_TOOLS_DIR/putgetdel $mp $kvs -d -s 100 -c 200  kvs.cn_maint_disable=1
    # Final state:
    #   Updated:   0..99
    #   Deleted: 100..299
    #   Put:     300..999
}
    
verify_keys () {
    # verify the three ranges before compaction
    cmd $HSE_TOOLS_DIR/putgetdel $mp $kvs -U -s   0 -c 100  kvs.cn_maint_disable=1
    cmd $HSE_TOOLS_DIR/putgetdel $mp $kvs -D -s 100 -c 200  kvs.cn_maint_disable=1
    cmd $HSE_TOOLS_DIR/putgetdel $mp $kvs -P -s 300 -c 700  kvs.cn_maint_disable=1
    # prove $HSE_TOOLS_DIR/putgetdel is actually verifying by asking it to verify 0..1000 and expecting failure
    cmd --exp-err-status $HSE_TOOLS_DIR/putgetdel $mp $kvs -P -s 0 -c 1000  kvs.cn_maint_disable=1
}

verify_shape_before () {
    # verify there are 8 kvsets in root node
    cmd $HSE_TOOLS_DIR/cn_metrics $mp $kvs
    cmd grep '^n.0,0,8' $LOG
}

verify_shape_after_spill () {
    # verify there are no kvsets in root node
    cmd $HSE_TOOLS_DIR/cn_metrics $mp $kvs
    cmd --exp-err-status grep '^n.0,0,0' $LOG
}

verify_shape_after_kv_compact () {
    # verify there is 1 kvset in root node
    cmd $HSE_TOOLS_DIR/cn_metrics $mp $kvs
    cmd grep '^n.0,0,1' $LOG
}

verify_shape_after_k_compact () {
    # verify there is 1 kvset in root node
    cmd $HSE_TOOLS_DIR/cn_metrics $mp $kvs
    cmd grep '^n.0,0,1' $LOG
}

# spill
setup
verify_shape_before
cmd $HSE_TOOLS_DIR/putbin $mp $kvs -n 100 kvs.cn_close_wait=1 kvs.cn_compaction_debug=-1
verify_shape_after_spill



# CRAP: we can't test k_compact or kv_compact easily because the root node is hard-coded to spill
exit 0


# k_compact
setup
verify_shape_before
cmd $HSE_TOOLS_DIR/putbin $mp $kvs -n 100 kvs.cn_close_wait=1 kvs.cn_compaction_debug=-1 \
    kvs.cn_compact_limit=100 kvs.cn_compact_spill=100 kvs.cn_compact_only=2
verify_shape_after_k_compact


# kv_compact
setup
verify_shape_before
cmd $HSE_TOOLS_DIR/putbin $mp $kvs -n 100 kvs.cn_close_wait=1 kvs.cn_compaction_debug=-1 \
    kvs.cn_compact_limit=100 kvs.cn_compact_spill=100 kvs.cn_compact_only=2 \
    kvs.cn_compact_waste=0
verify_shape_after_kv_compact

