#!/usr/bin/bash

#doc: Query fixed length ranges while updating random records.

kvs=$(new_kvs $mp pfx_len=8) || err

# Load
nthread=128
vlen=1024
npfx=8
nsfx=200000 # (npfx * nsfx) keys total
cmd range_read $mp $kvs -l -j$nthread -v$vlen -p$npfx -s$nsfx kvs-oparms cn_node_size_lo=32 cn_node_size_hi=32

cmd kvck $mp

# Query
nthread=32
duration=20 # seconds
range=10
cmd range_read $mp $kvs -e -b$range -j$nthread -v$vlen -p$npfx -s$nsfx -d$duration -V
cmd range_read $mp $kvs -e -b$range -j$nthread -v$vlen -p$npfx -s$nsfx -d$duration -V


