#!/usr/bin/bash

#doc: verify tombstones in root node hide keys in level 1 (see SBUSWNF-1265/PR-672)
keys=10

kvs=$(new_kvs $mp) || err

sp='[[:space:]]'

kvdb_oparms='kvdb-oparms csched_debug_mask=0xffffffff'

# Generate 8 kvsets in root node w/ duplicate data.
for ((i = 0; i < 8; i++)); do
    cmd putbin -c$keys $mp $kvs $kvdb_oparms kvs-oparms cn_maint_disable=1
done

# Let compaction run, which should spill all keys into level 1, then verify
# no kvsets in level 0
cmd putbin -n 1000 $mp $kvs kvs-oparms cn_close_wait=1 $kvdb_oparms
cmd cn_metrics $mp $kvs
check=$LOG
cmd --exp-err-status grep -P "^k${sp}+0,0,0${sp}" "$check"

# Validate keys found in level 1, w/ maint disabled.
cmd putbin -V -c$keys $mp $kvs $kvdb_oparms kvs-oparms cn_maint_disable=1

# Add tombstones, with maint disabled.  Verify that one kvset is in root node.
cmd putbin -D -c$keys $mp $kvs $kvdb_oparms kvs-oparms cn_maint_disable=1
cmd cn_metrics $mp $kvs
check=$LOG
cmd grep -P "^n${sp}+0,0,1${sp}" "$check"

# Validate keys, w/ maint disabled. Expect error since tombstones block.
cmd --exp-err-status putbin -V -c1 $mp $kvs $kvdb_oparms kvs-oparms cn_maint_disable=1


