#!/usr/bin/bash

#tdoc: quick mpool IO test using kmt (50%, 20% and 5% writes)

seconds=30

cmd kmt -i128 -t$seconds -bcDR -s1 -w50 -osecsz=4k -j$(nproc) mpool:$mp/capacity
cmd kmt -i128 -t$seconds -bcDR -s1 -w20 -osecsz=1m -j$(nproc) mpool:$mp/capacity
cmd kmt -i128 -t$seconds -bcDR -s1 -w5 -osecsz=32m -j$(nproc) mpool:$mp/capacity
