#!/usr/bin/bash

#doc: test to verify kvs drop functionality, specifically testing the edge condition where the last transactions are completely removed.

keys=10

kvs=$(new_kvs $mp) || err
kvs2=$(new_kvs $mp) || err


cmd $HSE_TOOLS_DIR/putbin -c$keys $mp $kvs
cmd $HSE_TOOLS_DIR/putbin -c$keys $mp $kvs2

# validate
cmd $HSE_TOOLS_DIR/putbin -V -c$keys $mp $kvs
cmd $HSE_TOOLS_DIR/putbin -V -c$keys $mp $kvs2

cmd "$HSE_CLI" kvs destroy $mp/$kvs2

# validate cndb and that cnid 1 keys exist
cmd $HSE_TOOLS_DIR/putbin -V -c$keys $mp $kvs

# get tree metrics
cmd $HSE_TOOLS_DIR/cndb_log $mp

# verify that cnid 2 is not present
cmd --exp-err-status grep 'cnid 2' $LOG


