#!/usr/bin/bash

#doc: test to verify kvs drop functionality, specifically testing the edge condition where the last transactions are completely removed.

keys=10

kvs=$(new_kvs $mp) || err
kvs2=$(new_kvs $mp) || err


cmd putbin -c$keys $mp $kvs
cmd putbin -c$keys $mp $kvs2

# validate
cmd putbin -V -c$keys $mp $kvs
cmd putbin -V -c$keys $mp $kvs2

cmd hse1 -C $mp kvs drop $kvs2

# validate cndb and that cnid 1 keys exist
cmd putbin -V -c$keys $mp $kvs

# get tree metrics
cmd cndb_log $mp

# verify that cnid 2 is not present
cmd --exp-err-status grep 'cnid 2' $LOG
