#!/usr/bin/bash

#doc: kvt compression test (transactional, snapshot isolation)

cpus=$(nproc)

cmd $HSE_TOOLS_DIR/kvt -i1m -T30,$((cpus * 2)) -cv -l0,16k -ovrunlen=5 -m1 $mp kvs.value_compression=lz4
cmd $HSE_TOOLS_DIR/kvt -Fi8k -T30,$((cpus * 2)) -cv -l1m -m1 -ovrunlen=3  $mp kvs.value_compression=lz4
cmd $HSE_TOOLS_DIR/kvt -Fi8m -T30,$((cpus * 2)) -cv -l0,16 -m1 -ovrunlen=1 $mp kvs.value_compression=lz4
cmd $HSE_TOOLS_DIR/kvt -T30,$((cpus * 2)) -cv -m1 $mp
  

