#!/usr/bin/bash

#doc: kmt large value test (SBUSWNF-2165)

kvs=$(new_kvs $mp) || err

# This test depends on having 1MiB values in vblocks at offsets that are not
# page-aligned.  Using a small number of value lengths make that a frequent
# occurrence, thus exposing the bug (or verifying the fix) more likely.

VLEN=-l1048532:1048576
KEYS=20k

# ingest w spill disabled
cmd $HSE_TOOLS_DIR/kmt $mp/$kvs -s1 $VLEN -i$KEYS kvs.cn_maint_disable=1

# verify no spill occurred
cmd $HSE_TOOLS_DIR/cn_metrics $mp $kvs
cmd --exp-err-status grep -q n.1, $LOG

# verify keys and values
cmd $HSE_TOOLS_DIR/kmt $mp/$kvs -s1 $VLEN -c kvs.cn_maint_disable=1

# spill
cmd $HSE_TOOLS_DIR/putbin $mp $kvs -n 1000 kvs.cn_close_wait=1
                                       
# verify spill has occurred
cmd $HSE_TOOLS_DIR/cn_metrics $mp $kvs
cmd grep -q n.1, $LOG

# verify keys and values
cmd $HSE_TOOLS_DIR/kmt $mp/$kvs -s1 $VLEN -c kvs.cn_maint_disable=1


