#!/usr/bin/bash

# Check cursor behaviour with corner cases.
# Note that this test depends on the
# way putbin creates its keys. Any change to that will affect the results of
# this test.

kvs=$(new_kvs $mp)

nkeys=1000

# load w/ little endian fmt keys
cmd putbin $mp $kvs -c$nkeys -e kvs-oparms cn_maint_disable=1

# create a cursor using the last key in pg 0 of the wbtree as a prefix
key=0x7f010000
cmd pscan $mp $kvs -p$key -c kvs-oparms cn_maint_disable=1
cnt=$(awk '{print($1);exit(0)}' $LOG)
[[ "$cnt" == "1" ]] ||
    err "Forward cursor didn't find key '$key'"

cmd pscan $mp $kvs -p$key -c -r kvs-oparms cn_maint_disable=1
cnt=$(awk '{print($1);exit(0)}' $LOG)
[[ "$cnt" == "1" ]] ||
    err "Reverse cursor didn't find key '$key'"
