#!/usr/bin/bash

#doc: quick longtest focused on cn

# add 3 KVSes to the KVDB
kvs1=$(new_kvs $mp) || err
kvs2=$(new_kvs $mp) || err
kvs3=$(new_kvs $mp) || err

threads=4
keys=100000
seed=$RANDOM

# This test requires '--once' to ensure each thread of each invocation of
# $HSE_TOOLS_DIR/longtest runs through exactly one iteration.
for (( phase = 0; phase <= 9; phase++ )); do
    cmd $HSE_TOOLS_DIR/longtest $mp $kvs2 -t $threads -c $keys --mphase $((1<<phase)) --verify 100 --seed $seed --once -v
    cmd $HSE_TOOLS_DIR/cn_metrics $mp $kvs2
done



