#!/usr/bin/bash

#doc: 60s longtest with sync without cursors

kvs=$(new_kvs $mp) || err

keys=$((1*1000*1000))
threads=4
seconds=60

# use skewed distribution, and tell last thread (with fewest keys) to sync once per iteration.
args=()
args+=(-t $threads -s $seconds -c $keys -v)
args+=(--poly=4) # skewed distribution
args+=(--sync=$((threads-1)))
args+=(--verify=100)
args+=(kvs.cn_compaction_debug=3)

cmd longtest $mp $kvs "${args[@]}"
cmd cn_metrics $mp $kvs




