#!/usr/bin/bash

cmd mdctest kvdb.capdir=${HSE_STORAGE_PATH}

cmd mdcperf -r 64 -c $((32 * 1024 *1024)) -v kvdb.capdir=${HSE_STORAGE_PATH}
cmd mdcperf -r 64 -c $((8 * 1024 * 1024)) -v -s kvdb.capdir=${HSE_STORAGE_PATH}

cmd mdcperf -r 4096 -c $((1024 * 1024 * 1024)) -v kvdb.capdir=${HSE_STORAGE_PATH}
cmd mdcperf -r 4096 -c $((256 * 1024 * 1024)) -v -s kvdb.capdir=${HSE_STORAGE_PATH}
