#!/usr/bin/bash

cmd mdctest kvdb.storage_path=${HSE_STORAGE_PATH}

cmd mdcperf -r 64 -c $((32 * 1024 *1024)) -v kvdb.storage_path=${HSE_STORAGE_PATH}
cmd mdcperf -r 64 -c $((8 * 1024 * 1024)) -v -s kvdb.storage_path=${HSE_STORAGE_PATH}

cmd mdcperf -r 4096 -c $((1024 * 1024 * 1024)) -v kvdb.storage_path=${HSE_STORAGE_PATH}
cmd mdcperf -r 4096 -c $((256 * 1024 * 1024)) -v -s kvdb.storage_path=${HSE_STORAGE_PATH}
