#!/usr/bin/bash

#doc: test ptree semantics

kvs=$(new_kvs $mp kvs.pfx_len=8) || err

# Test 1: Should result in 2 kblocks
keys=1300000
ptombs=300000

rparams='kvs.cn_maint_disable=1'

cmd $HSE_TOOLS_DIR/ptree-overload $mp $kvs -k $keys -p $ptombs ${rparams}
$HSE_TOOLS_DIR/cn_metrics $mp $kvs
nkvset=$($HSE_TOOLS_DIR/cn_metrics $mp $kvs | grep -c ^k)
[[ $nkvset == 1 ]] || err "Expected only one kvset. Found $nkvset kvsets"

nkblks=$($HSE_TOOLS_DIR/cn_metrics $mp $kvs | awk '$1 ~ /^k/ {print $14}')
[[ $nkblks == 2 ]] || err "Expected two kblocks. Found $nkblks kblocks"

# Test 2: Should result in 1 kblock
kvs=$(new_kvs $mp kvs.pfx_len=8) || err
keys=1000000
ptombs=300000

cmd $HSE_TOOLS_DIR/ptree-overload $mp $kvs -k $keys -p $ptombs ${rparams}
$HSE_TOOLS_DIR/cn_metrics $mp $kvs
nkvset=$($HSE_TOOLS_DIR/cn_metrics $mp $kvs | grep -c ^k)
[[ $nkvset == 1 ]] || err "Expected only one kvset. Found $nkvset kvsets"

nkblks=$($HSE_TOOLS_DIR/cn_metrics $mp $kvs | awk '$1 ~ /^k/ {print $14}')
[[ $nkblks == 1 ]] || err "Expected one kblock. Found $nkblks kblocks"
