#!/usr/bin/bash

#doc: test HSE CLI version command

cmd hse -Vv

# Check for three lines of output
count=$(wc -l < "$LOG")
if [[ "$count" != 3 ]]; then
    err "Expect three lines of output from command:" \
        "  hse -Vv" \
        "Found $count lines in log file:" \
        "  $LOG"
fi

# Check output fields
cmd sed -ne 's/:.*//p' "$LOG"
cmd sort "$LOG"
fields=$(xargs echo < "$LOG")
[[ "$fields" == "sha tag version" ]] ||
    err "Expect fields sha, tag and version" \
        "Found: $fields"
