#!/usr/bin/bash

#doc: use putgetdel to test zero-length values

keys=100
kvs=$(new_kvs $mp) || err

# Six step test:
# - Put keys with 0-byte values
# - Verify those keys can be found and have vlen==0
# - Update same keys with 10-byte values
# - Verify
# - Update same keys with 0-byte values
# - Verify
cmd putgetdel $mp $kvs -c $keys --vlen 0   --put
cmd putgetdel $mp $kvs -c $keys --vlen 0  --vput
cmd putgetdel $mp $kvs -c $keys --vlen 10  --put
cmd putgetdel $mp $kvs -c $keys --vlen 10 --vput
cmd putgetdel $mp $kvs -c $keys --vlen 0   --put
cmd putgetdel $mp $kvs -c $keys --vlen 0  --vput
