#!/bin/sh
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2020 Micron Technology, Inc.  All rights reserved.
#
# https://www.debian.org/doc/debian-policy/ch-matainerscripts.html

PROG=${0##*/}
PKG=$(basename ${0%.*})

echo "${PROG} [$*]"

PERMS=666
MAXSIZE=10M # When to rotate logs
MINSIZE=9M  # Until when not to rotate logs
ARCHIVE_CNT=100 # Max compressed archive files to maintain at any point in time

conf="# Config to rotate dt.log
/var/log/hse/dt.log{
    create $PERMS
    compress
    notifempty
    rotate $ARCHIVE_CNT
    nomissingok
    weekly
    size $MAXSIZE
    minsize $MINSIZE
    maxage 90
}
"
case $1 in
    configure)
        # add jni lib to cache
        /sbin/ldconfig

        # create dt.log
        conf_hse="/etc/logrotate.d/hse"
        dtlog="/var/log/hse/dt.log"

        # logrotate config
        rm -f $conf_hse
        printf "$conf" > $conf_hse

        # log file
        mkdir -p /var/log/hse
        touch $dtlog
        chmod $PERMS $dtlog
        ;;

    *)
esac

exit 0
