#!/bin/sh
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2020 Micron Technology, Inc.  All rights reserved.
#
# https://www.debian.org/doc/debian-policy/ch-matainerscripts.html

PROG=${0##*/}
PKG=$(basename ${0%.*})

echo "${PROG} [$*]"

case $1 in
    remove|purge)
        ;;

    abort-upgrade)
        ;;

    *)
        ;;
esac

exit 0


