#!/usr/bin/env sh

set -e

# Path to source root. MESON_SOURCE_ROOT is set during script runs, but this
# script won't always be run through Meson.
source_root=$(realpath $(dirname $(dirname $(dirname $0))))

for hook in pre-commit; do
	ln -s $source_root/scripts/dev/$hook $source_root/.git/hooks/$hook
done
