name: ABI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "include/**.h"
      - "include/**.h.in"
      - "lib/**.c"
      - "lib/**.h"
      - "**/meson.build"
      - .github/workflows/abicheck.yaml
      - meson_options.txt
      - VERSION

concurrency:
  group: ${{ github.workflow }}-ignore-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  abicheck:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"
