name: Builds

on:
  push:
    branches:
      - master
      - v2.*
    paths:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/**"
      - "docs/**"
      - "!.github/workflows/builds.yaml"
      - .clang-format
      - .gitattributes
      - .gitignore
      - .shellcheckrc
      - LICENSE
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/**"
      - "docs/**"
      - "!.github/workflows/builds.yaml"
      - .clang-format
      - .gitattributes
      - .gitignore
      - .shellcheckrc
      - LICENSE

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        toolchain: [gcc, clang]
        buildtype: [release, debug]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"

  fedora:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-tag: [35]
        toolchain: [gcc, clang]
        buildtype: [release, debug]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"

  almalinux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-tag: [8]
        toolchain: [gcc, clang]
        buildtype: [release, debug]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"

  architectures:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]
        arch: [s390x]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"

  asan-ubsan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"

  subprojects:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"
