# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2022 Micron Technology, Inc.

name: Builds

on:
  push:
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    paths-ignore:
      - "**.c"
      - "**.h"
      - "**.h.in"
      - "**/meson.build"
      - "cross/*.ini"
      - "scripts/build/*"
      - "subprojects/*.wrap"
      - "suppressions/**.supp"
      - "tests/**.py"
      - "tests/**.sh"
      - .github/workflows/builds.yaml
      - docs/openapi.json
      - meson_options.txt
      - VERSION
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.c"
      - "**.h"
      - "**.h.in"
      - "**/meson.build"
      - "cross/*.ini"
      - "scripts/build/*"
      - "subprojects/*.wrap"
      - "suppressions/**.supp"
      - "tests/**.py"
      - "tests/**.sh"
      - .github/workflows/builds.yaml
      - docs/openapi.json
      - meson_options.txt
      - VERSION

concurrency:
  group: ${{ github.workflow }}-ignore-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  normal:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - almalinux-8
          - almalinux-9
          - cross-s390x
          - fedora-37
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
        toolchain: [gcc, clang]
        buildtype: [release, debug]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}/${{ matrix.image }}/${{ matrix.toolchain }}/${{ matrix.buildtype }}"

  asan-ubsan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}/${{ matrix.buildtype }}"

  lto:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}/${{ matrix.buildtype }}"
