name: Builds

on:
  push:
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    paths:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/**"
      - "docs/**"
      - "!.github/workflows/builds.yaml"
      - .clang-format
      - .gitattributes
      - .github/dependabot.yaml
      - .gitignore
      - .shellcheckrc
      - LICENSE
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/**"
      - "docs/**"
      - "!.github/workflows/builds.yaml"
      - .clang-format
      - .gitattributes
      - .github/dependabot.yaml
      - .gitignore
      - .shellcheckrc
      - LICENSE

concurrency:
  group: ${{ github.workflow }}-ignore-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-tag: ["18.04", "20.04", "22.04"]
        toolchain: [gcc, clang]
        buildtype: [release, debug]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"

  fedora:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-tag: [36]
        toolchain: [gcc, clang]
        buildtype: [release, debug]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"

  almalinux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-tag: [8, 9]
        toolchain: [gcc, clang]
        buildtype: [release, debug]
    if: ${{ github.event_name != 'release' }}

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"

  architectures:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]
        arch: [s390x]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"

  asan-ubsan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"

  subprojects:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"
