name: Builds

on:
  push:
    branches:
      - master
      - v2.*
    paths-ignore:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/**"
      - "docs/**"
      - "!.github/workflows/builds.yaml"
      - .clang-format
      - .gitattributes
      - .gitignore
      - .shellcheckrc
      - LICENSE
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/**"
      - "docs/**"
      - "!.github/workflows/builds.yaml"
      - .clang-format
      - .gitattributes
      - .gitignore
      - .shellcheckrc
      - LICENSE

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

env:
  MESON_TESTTHREADS: 1

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.image-tag }}
    strategy:
      fail-fast: false
      matrix:
        image-tag: ["18.04", "20.04"]
        toolchain: [gcc, clang]
        buildtype: [release, debug]
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout HSE
        uses: actions/checkout@v3

      - name: Checkout hse-java
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-java
          path: subprojects/hse-java
          ref: ${{ github.base_ref || github.ref }}

      - name: Checkout hse-python
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-python
          path: subprojects/hse-python
          ref: ${{ github.base_ref || github.ref }}

      - name: Post-checkout
        run: |
          for b in hse-java hse-python; do
            git -C "subprojects/$b" checkout ${{ github.head_ref }} || true
          done

      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: "8"
          cache: maven

      - name: Initialize
        run: |
          apt-get -y update
          apt-get -y install build-essential python3 python3-pip ninja-build \
            pkg-config gawk libbsd-dev libmicrohttpd-dev liburcu-dev \
            libyaml-dev libcurl4-openssl-dev libmongoc-dev libbson-dev \
            libssl-dev libsasl2-dev libncurses-dev maven
          python3 -m pip install Cython

      - name: Get Meson on ubuntu-18.04
        if: ${{ matrix.image-tag == '18.04' }}
        run: |
          apt-get -y install python3.7
          python3.7 -m pip install meson==0.62.2

      - name: Get Meson on Ubuntu 20.04
        if: ${{ matrix.image-tag == '20.04' }}
        run: |
          python3 -m pip install meson==0.62.2

      # Download all dependencies up front if cache wasn't hit. Will keep
      # Maven from downloading dependencies during the test phase which could
      # cause tests to timeout.
      - name: Download Maven Dependencies
        if: steps.setup-java.outputs.cache-hit != 'true'
        run: |
          mvn --file subprojects/hse-java/pom.xml dependency:go-offline

      - name: Setup gcc toolchain
        if: ${{ matrix.toolchain == 'gcc' }}
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
          apt-get -y install gcc g++

        # Fix false warnings by installing newer version in 18.04
      - name: Setup clang toolchain on Ubuntu 18.04
        if: ${{ matrix.toolchain == 'clang' && matrix.image-tag == '18.04' }}
        run: |
          echo "CC=clang-10" >> $GITHUB_ENV
          echo "CXX=clang++-10" >> $GITHUB_ENV
          apt-get -y install clang-10

        # Ignore deprecation warnings on 20.04 due to:
        #     https://github.com/cython/cython/issues/3474
      - name: Setup clang toolchain on Ubuntu 20.04
        if: ${{ matrix.toolchain == 'clang' && matrix.image-tag == '20.04' }}
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "CFLAGS=-Wno-deprecated ${CFLAGS}" >> $GITHUB_ENV
          apt-get -y install clang

        # Tools are disabled due to deprecated support in Meson for CMake
        # versions this old.
      - name: Setup
        run: |
          meson builddir --fatal-meson-warnings -Dwerror=true \
            -Dbuildtype=${{ matrix.buildtype }} -Dtools=disabled \
            -Ddocs=disabled -Dbindings=all

      - name: Build
        run: |
          ninja -C builddir

      - name: Test
        run: |
          ulimit -c unlimited
          meson test -C builddir --setup=ci --print-errorlogs --no-stdsplit

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}-${{ matrix.image-tag }}-${{ matrix.toolchain }}-${{ matrix.buildtype }}
          path: |
            builddir/meson-logs/
            /var/log/messages
            /var/log/syslog

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:${{ matrix.image-tag }}
    strategy:
      fail-fast: false
      matrix:
        image-tag: [36]
        toolchain: [gcc, clang]
        buildtype: [release, debug]

    steps:
      - name: Checkout HSE
        uses: actions/checkout@v3

      - name: Checkout hse-java
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-java
          path: subprojects/hse-java
          ref: ${{ github.base_ref || github.ref }}

      - name: Checkout hse-python
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-python
          path: subprojects/hse-python
          ref: ${{ github.base_ref || github.ref }}

      - name: Post-checkout
        run: |
          for b in hse-java hse-python; do
            git -C "subprojects/$b" checkout ${{ github.head_ref }} || true
          done

      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: "17"
          cache: maven

      - name: Initialize
        run: |
          dnf group install -y --with-optional \
            "C Development Tools and Libraries"
          dnf install -y git ninja-build python-unversioned-command \
            libmicrohttpd-devel userspace-rcu-devel libyaml-devel libbsd-devel \
            libcurl-devel libpmem-devel xz mongo-c-driver libbson \
            openssl-devel cyrus-sasl-devel ncurses-devel maven python3-devel \
            python3-Cython libxml2 libxslt
          python3 -m pip install meson==0.62.2

      # Download all dependencies up front if cache wasn't hit. Will keep
      # Maven from downloading dependencies during the test phase which could
      # cause tests to timeout.
      - name: Download Maven Dependencies
        if: steps.setup-java.outputs.cache-hit != 'true'
        run: |
          mvn --file subprojects/hse-java/pom.xml dependency:go-offline

      - name: Setup gcc toolchain
        if: ${{ matrix.toolchain == 'gcc' }}
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
          dnf install -y gcc gcc-c++

      - name: Setup clang toolchain
        if: ${{ matrix.toolchain == 'clang' }}
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          dnf install -y clang

      - name: Setup
        run: |
          meson builddir --fatal-meson-warnings -Dwerror=true\
            -Dbuildtype=${{ matrix.buildtype }} -Dtools=enabled -Dpmem=enabled \
            -Ddocs=disabled -Dbindings=all

      - name: Build
        run: |
          ninja -C builddir

      - name: Test
        run: |
          ulimit -c unlimited
          meson test -C builddir --setup=ci --print-errorlogs --no-stdsplit

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}-${{ matrix.image-tag }}-${{ matrix.toolchain }}-${{ matrix.buildtype }}
          path: |
            builddir/meson-logs/
            /var/log/messages
            /var/log/syslog

  almalinux:
    runs-on: ubuntu-latest
    container:
      image: almalinux:${{ matrix.image-tag }}
    strategy:
      fail-fast: false
      matrix:
        image-tag: [8]
        toolchain: [gcc, clang]
        buildtype: [release, debug]

    steps:
      - name: Checkout HSE
        uses: actions/checkout@v3

      - name: Checkout hse-java
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-java
          path: subprojects/hse-java
          ref: ${{ github.base_ref || github.ref }}

      - name: Checkout hse-python
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-python
          path: subprojects/hse-python
          ref: ${{ github.base_ref || github.ref }}

      - name: Post-checkout
        run: |
          for b in hse-java hse-python; do
            git -C "subprojects/$b" checkout ${{ github.head_ref }} || true
          done

      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: "17"
          cache: maven

      - name: Initialize
        run: |
          dnf install -y dnf-plugins-core epel-release
          dnf config-manager --set-enabled powertools
          dnf group install -y --with-optional "Development Tools"
          dnf install -y git ninja-build libmicrohttpd-devel \
            userspace-rcu-devel libyaml-devel libbsd-devel libcurl-devel \
            libpmem-devel xz mongo-c-driver libbson openssl-devel \
            cyrus-sasl-devel ncurses-devel maven python39 python39-devel \
            libxml2 libxslt
          python3 -m pip install meson==0.62.2 Cython

      # Download all dependencies up front if cache wasn't hit. Will keep
      # Maven from downloading dependencies during the test phase which could
      # cause tests to timeout.
      - name: Download Maven Dependencies
        if: steps.setup-java.outputs.cache-hit != 'true'
        run: |
          mvn --file subprojects/hse-java/pom.xml dependency:go-offline

      - name: Setup gcc toolchain
        if: ${{ matrix.toolchain == 'gcc' }}
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
          dnf install -y gcc gcc-c++

      - name: Setup clang toolchain
        if: ${{ matrix.toolchain == 'clang' }}
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          dnf install -y clang

      - name: Setup
        run: |
          meson builddir --fatal-meson-warnings -Dwerror=true \
            -Dbuildtype=${{ matrix.buildtype }} -Dtools=enabled \
            -Ddocs=disabled -Dbindings=all

      - name: Build
        run: |
          ninja -C builddir

      - name: Test
        run: |
          ulimit -c unlimited
          meson test -C builddir --setup=ci --print-errorlogs --no-stdsplit

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}-${{ matrix.image-tag }}-${{ matrix.toolchain }}-${{ matrix.buildtype }}
          path: |
            builddir/meson-logs/
            /var/log/messages
            /var/log/syslog

  architectures:
    runs-on: ubuntu-latest
    container:
      image: debian:11
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]
        arch: [s390x]

    steps:
      - name: Checkout HSE
        uses: actions/checkout@v3

      - name: Checkout hse-java
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-java
          path: subprojects/hse-java
          ref: ${{ github.base_ref || github.ref }}

      - name: Checkout hse-python
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-python
          path: subprojects/hse-python
          ref: ${{ github.base_ref || github.ref }}

      - name: Post-checkout
        run: |
          for b in hse-java hse-python; do
            git -C "subprojects/$b" checkout ${{ github.head_ref }} || true
          done

      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: "17"
          cache: maven

      - name: Initialize
        run: |
          dpkg --add-architecture ${{ matrix.arch }}
          apt-get -y update
          apt-get -y install python3 python3-pip pkg-config ninja-build cmake \
            gawk build-essential crossbuild-essential-${{ matrix.arch }} \
            libpython3-dev:${{ matrix.arch }} liburcu-dev:${{ matrix.arch }} \
            libcurl4-openssl-dev:${{ matrix.arch }} \
            libbsd-dev:${{ matrix.arch }} libmicrohttpd-dev:${{ matrix.arch }} \
            libyaml-dev:${{ matrix.arch }} libmongoc-dev:${{ matrix.arch }} \
            libbson-dev:${{ matrix.arch }} libncurses-dev:${{ matrix.arch }} \
            maven
          python3 -m pip install meson==0.62.2 Cython

      # Download all dependencies up front if cache wasn't hit. Will keep
      # Maven from downloading dependencies during the test phase which could
      # cause tests to timeout.
      - name: Download Maven Dependencies
        if: steps.setup-java.outputs.cache-hit != 'true'
        run: |
          mvn --file subprojects/hse-java/pom.xml dependency:go-offline

      - name: Setup
        run: |
          meson builddir --fatal-meson-warnings -Dwerror=true --cross-file \
            cross/${{ matrix.arch }}.ini --cross-file cross/common.ini \
            -Dbuildtype=${{ matrix.buildtype }} -Dtools=enabled \
            -Ddocs=disabled -Dbindings=all

      - name: Build
        run: |
          ninja -C builddir

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}-${{ matrix.arch }}-${{ matrix.buildtype }}
          path: |
            builddir/meson-logs/

  asan-ubsan:
    runs-on: ubuntu-latest
    container:
      image: fedora:36
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]

    steps:
      - name: Checkout HSE
        uses: actions/checkout@v3

      - name: Initialize
        run: |
          dnf group install -y --with-optional \
            "C Development Tools and Libraries"
          dnf install -y git ninja-build python3-pip libmicrohttpd-devel \
            userspace-rcu-devel libyaml-devel libbsd-devel libcurl-devel \
            libpmem-devel xz mongo-c-driver libbson openssl-devel \
            cyrus-sasl-devel ncurses-devel libxml2-devel libxslt-devel \
            libasan libubsan
          python3 -m pip install meson==0.62.2

      - name: Setup
        run: |
          meson builddir -Dwerror=true -Dbuildtype=${{ matrix.buildtype }} \
            -Db_sanitize=address,undefined -Dtools=enabled -Ddocs=disabled \
            -Dbindings=none

      - name: Build
        run: |
          ninja -C builddir

      - name: Test
        run: |
          ulimit -c unlimited
          meson test -C builddir --setup=ci --print-errorlogs --no-stdsplit

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}-${{ matrix.buildtype }}
          path: |
            builddir/meson-logs/
            /var/log/messages
            /var/log/syslog

  subprojects:
    runs-on: ubuntu-latest
    container:
      image: fedora:36

    steps:
      - name: Checkout HSE
        uses: actions/checkout@v3

      - name: Checkout hse-java
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-java
          path: subprojects/hse-java
          ref: ${{ github.base_ref || github.ref }}

      - name: Checkout hse-python
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-python
          path: subprojects/hse-python
          ref: ${{ github.base_ref || github.ref }}

      - name: Post-checkout
        run: |
          for b in hse-java hse-python; do
            git -C "subprojects/$b" checkout ${{ github.head_ref }} || true
          done

      - name: Setup Java
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: "17"
          cache: maven

      - name: Initialize
        run: |
          dnf group install -y --with-optional \
            "C Development Tools and Libraries"
          dnf install -y git python3-pip ninja-build pkg-config ncurses-devel \
            python3-devel python3-Cython maven
          python3 -m pip install meson==0.62.2

      # Download all dependencies up front if cache wasn't hit. Will keep
      # Maven from downloading dependencies during the test phase which could
      # cause tests to timeout.
      - name: Download Maven Dependencies
        if: steps.setup-java.outputs.cache-hit != 'true'
        run: |
          mvn --file subprojects/hse-java/pom.xml dependency:go-offline

      - name: Setup
        run: |
          meson builddir --fatal-meson-warnings -Dwerror=true \
            -Dwrap_mode=forcefallback -Dtools=enabled -Ddocs=disabled \
            -Dbindings=all

      - name: Build
        run: |
          ninja -C builddir

      - name: Test
        run: |
          ulimit -c unlimited
          meson test -C builddir --setup=ci --print-errorlogs --no-stdsplit

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}
          path: |
            builddir/meson-logs/
            /var/log/messages
            /var/log/syslog
