name: clang-tidy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    paths:
      - "**.c"
      - "**.h"
      - "**.h.in"
      - .clang-tidy
      - .github/workflows/clang-tidy.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hse-project/ci-images/fedora-36:${{ github.base_ref }}
    strategy:
      fail-fast: false
      matrix:
        buildtype: [debug, release]

    steps:
      - name: Checkout HSE
        uses: actions/checkout@v3

      - name: Cache Meson packagecache
        uses: actions/cache@v3
        with:
          path: subprojects/packagecache
          key: meson-packagecache-fedora-36-${{ hashFiles('subprojects/*.wrap') }}

      - name: Setup clang toolchain
        run: |
          echo "CC=clang" >> "$GITHUB_ENV"
          echo "CXX=clang++" >> "$GITHUB_ENV"

      - name: Setup
        run: |
          meson builddir --fatal-meson-warnings --werror \
            --buildtype=${{ matrix.buildtype }} -Dtools=enabled -Dpmem=enabled \
            -Ddocs=disabled -Dbindings=none

      - name: Build
        run: |
          ninja -C builddir

      - name: Run clang-tidy
        run: |
          ninja -C builddir clang-tidy
