# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2023 Micron Technology, Inc.

name: ClangFormat

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.c"
      - "**.h"
      - "**.h.in"
      - "!subprojects/*"
      - .github/workflows/clang-format.yaml

concurrency:
  group: ${{ github.workflow }}-ignore-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"
