name: Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel jobs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          ignore_sha: true
          workflow_id: abicheck.yaml,builds.yaml,checkoss.yaml,docs.yaml,shellcheck.yaml
