name: Docs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    paths-ignore:
      - "docs/**"
      - "include/**/*.h"
      - "include/**/*.h.in"
      - .github/workflows/docs.yaml

concurrency:
  group: ${{ github.workflow }}-ignore-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"
