name: Docs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    paths:
      - "docs/**"
      - "include/**/*.h"
      - "include/**/*.h.in"
      - .github/workflows/docs.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hse-project/ci-images/fedora-37:${{ github.base_ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: |
          meson setup builddir --fatal-meson-warnings -Dwerror=true -Ddocs=enabled \
            -Dtests=false -Dtools=disabled -Dbindings=none -Dcli=false \
            -Dsamples=false

      - name: Build
        run: |
          meson compile -C builddir docs
