name: Docs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "docs/**"
      - "include/**/*.h"
      - "include/**/*.h.in"
      - .github/workflows/docs.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: fedora:36

    steps:
      - uses: actions/checkout@v3

      - name: Initialize
        run: |
          dnf group install -y --with-optional \
            "C Development Tools and Libraries"
          dnf install -y python3-pip git ninja-build libmicrohttpd-devel \
            userspace-rcu-devel libyaml-devel libbsd-devel libcurl-devel \
            libpmem-devel doxygen
          python3 -m pip install meson==0.62.2

      - name: Setup
        run: |
          meson builddir --fatal-meson-warnings -Dwerror=true -Ddocs=enabled \
            -Dtests=false -Dtools=disabled -Dbindings=none -Dcli=false \
            -Dsamples=false -Ddb_bench=false

      - name: Build
        run: |
          meson compile -C builddir docs
