# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2022 Micron Technology, Inc.

name: Docs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    paths:
      - "docs/doxygen/**"
      - "include/**.h"
      - "include/**.h.in"
      - .github/workflows/docs.yaml
      - docs/meson.build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hse-project/ci-images/fedora-37:${{ github.base_ref }}

    steps:
      - name: Checkout HSE
        uses: actions/checkout@v3

      - name: Cache Meson packagecache
        uses: actions/cache@v3
        with:
          path: subprojects/packagecache
          key: meson-packagecache-fedora-37-${{ hashFiles('subprojects/*.wrap') }}

      - name: Setup
        run: |
          meson setup builddir --fatal-meson-warnings -Dwerror=true \
            -Ddocs=enabled -Dtests=false -Dtools=disabled -Dbindings=none \
            -Dcli=false -Dsamples=false

      - name: Build
        run: |
          meson compile -C builddir docs
