name: Docs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**'
      - 'include/**/*.h'

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize
        run: |
          dnf install -y git ninja-build meson libmicrohttpd-devel \
            userspace-rcu-devel libyaml-devel libbsd-devel libcurl-devel \
            libpmem-devel

      - name: Setup
        run: |
          meson builddir --fatal-meson-warnings -Dwerror=true -Ddocs=enabled \
            -Dtests=false -Dtools=disabled -Dbindings=none -Dcli=false \
            -Dsamples=false -Ddb_bench=false

      - name: Build
        run: |
          meson compile -C builddir doxygen
