name: Nightly Testing

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to use"
        required: true
        default: "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

env:
  MESON_TESTTHREADS: 1

jobs:
  nightly_ub:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        buildtype: [release, debug]

    steps:
      - name: Freeing up disk space on CI system
        run: |
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm \
            google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          echo "Removing large directories"
          # deleting 15GB
          rm -rf /usr/share/dotnet/
          df -h

      - name: Initialize
        run: |
          sudo apt-get update
          sudo apt-get install build-essential ninja-build pkg-config \
            libbsd-dev openjdk-8-jdk libmicrohttpd-dev liburcu-dev libyaml-dev \
            liblz4-dev libcurl4-openssl-dev libmongoc-1.0-0 libbson-1.0-0 \
            libssl-dev libsasl2-dev
          sudo python3 -m pip install meson==0.62.2 Cython

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Checkout hse-python
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-python
          path: subprojects/hse-python

      - name: Post-checkout
        run: |
          for b in hse-python; do
            git -C "subprojects/$b" checkout ${{ github.head_ref }} || true
          done

      - name: Setup
        run: |
          meson builddir --fatal-meson-warnings -Dwerror=true \
            -Dbuildtype=${{ matrix.buildtype }} -Dtools=enabled \
            -Ddocs=disabled -Dbindings=all

      - name: Test
        run: |
          meson test -C builddir --suite=nightly-small --print-errorlogs \
            --no-stdsplit

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-artifact-ubuntu-${{ matrix.buildtype }}
          path: |
            builddir/meson-logs/
            /var/log/messages
            /var/log/syslog
            /var/log/kern.log
