name: Nightly Testing

on:
  pull_request:
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    paths:
      - .github/workflows/nightly_testing.yaml
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to use"
        required: true
        default: "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

env:
  MESON_TESTTHREADS: 1

jobs:
  determine-tag:
    runs-on: ubuntu-latest
    continue-on-error: false
    outputs:
      tag: ${{ steps.determine-tag.outputs.tag }}

    steps:
      - name: Determine tag
        id: determine-tag
        run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            echo "::set-output name=tag::$GITHUB_BASE_REF"
          else
            echo "::set-output name=tag::$GITHUB_REF_NAME"
          fi

  nightly_ub:
    runs-on: ubuntu-latest
    needs:
      - determine-tag
    container:
      image: ghcr.io/hse-project/ci-images/ubuntu-20.04:${{ needs.determine-tag.outputs.tag }}
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]

    steps:
      - name: Checkout HSE
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Determine branches
        id: determine-branches
        shell: sh +e {0}
        run: |
          for p in hse-java hse-python; do
            branch=master
            if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
              git ls-remote --exit-code --heads \
                "https://github.com/hse-project/$p.git" "$GITHUB_HEAD_REF" \
                > /dev/null

              if [ $? -eq 0 ]; then
                branch="$GITHUB_HEAD_REF"
              fi
            elif [ "$GITHUB_EVENT_NAME" = "release" ]; then
              branch=$(git rev-parse --abbrev-ref HEAD)
            else
              git ls-remote --exit-code --heads \
                "https://github.com/hse-project/$p.git" "$GITHUB_REF" \
                > /dev/null

              if [ $? -eq 0 ]; then
                branch="$GITHUB_REF_NAME"
              fi
            fi

            echo "::set-output name=$p::$branch"
          done

      - name: Checkout hse-java
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-java
          path: subprojects/hse-java
          ref: ${{ steps.determine-branches.outputs.hse-java }}

      - name: Checkout hse-python
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse-python
          path: subprojects/hse-python

      - name: Cache Meson packagecache
        uses: actions/cache@v3
        with:
          path: subprojects/packagecache
          key: meson-packagecache-ubuntu-20.04-${{ hashFiles('subprojects/*.wrap') }}

      - name: Setup
        run: |
          meson setup builddir --fatal-meson-warnings --werror \
            --buildtype=${{ matrix.buildtype }} -Dtools=enabled \
            -Ddocs=disabled -Dbindings=all

      - name: Test
        run: |
          meson test -C builddir --suite=nightly-small --print-errorlogs \
            --no-stdsplit

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-artifact-ubuntu-${{ matrix.buildtype }}
          path: |
            builddir/meson-logs/
            /var/log/messages
            /var/log/syslog
            /var/log/kern.log
