# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2023 Micron Technology, Inc.

name: REUSE

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout HSE
      uses: actions/checkout@v4

    - name: Lint
      uses: fsfe/reuse-action@v2
      with:
        args: --include-meson-subprojects lint
