name: ShellCheck

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.sh'
      - 'scripts/git-hooks/*'

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize
        run: |
          dnf install -y findutils ShellCheck

      - name: Lint
        run: |
          ./scripts/dev/shellcheck.sh
