# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2021 Micron Technology, Inc.

name: ShellCheck

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.sh"
      - "scripts/git-hooks/*"
      - .github/workflows/shellcheck.yaml
      - .shellcheckrc

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: fedora:36

    steps:
      - uses: actions/checkout@v4

      - name: Initialize
        run: |
          dnf install -y findutils ShellCheck

      - name: Lint
        run: |
          ./scripts/dev/shellcheck.sh
