name: ShellCheck

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.sh"
      - "scripts/git-hooks/*"
      - .github/workflows/shellcheck.yaml
      - .shellcheckrc

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"
